name: FloorIsLava
main: com.gmail.tracebachi.floorislava.FloorIsLavaPlugin
version: 2.9.1
authors: [Trace Bachi (BigBossZee), Jeremy Lugo (Refrigerbater)]
depend: [Vault, HolographicDisplays]
commands:
  floor:
    description: Main FIL command.
  floorbooster:
    description: FIL command for arena boosters.
  floorholo:
    description: FIL command for leaderboards.
  mfloor:
    description: Main FIL management command.
permissions:
  FloorIsLava.Staff:
    description: Allows the user to control FIL start-stop-reload-enable-disable.
